# -*- coding: utf-8 -*-
"""DSA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OfH3lIJwP_UnsXh9DsKqtDAsmbKw1tN9
"""

math=50
pi=0.3
name="vinay"
result=True
print(type(name))
print(type(pi))
print(type(math))
print(type(result))
print(id(name))
print(id(pi))
print(id(math))

math = 50
chem = 50
phy = 50
hindi = 40
print(id(hindi))
print(id(phy))
print(id(math))
print(id(chem))

list = [[1,2,3],
[4,5,6],
[7,8,9]]

print(2+2)
print("2"+"2")
val1 = input("enter value of val1 :") #input fun by default accept only string value
val2 = input("enter value of val2 :")
print(val1+val2)

val1 = int(input("enter value of val1 :"))
val2 = int(input("enter value of val2 :"))
print(val1+val2)

print(int(3.14))
print(int(True))
print(int(False))
print(int("4"))

print(int(10+5j)) #we can not convert complex value to int
print(int("4.3")) #we can not convert floating point value string to int
print(int("vinay"))

print(float(3))#3.0
#print(float(50+2j)) #we can not convert complex no. value to float
print(float(True))#1.0
print(float(False))#0.0
print(float(4.22))
print(float("4"))
#print(float("vinay")) #we can not convert string.

print(complex(4.22))
print(complex(True))
print(complex(False))
print(complex("5"))
print(complex(5.4))
#print(complex("name"))
print(complex(5,-3))
print(complex(True, False))

print(bool())

print(bool(0))
print(bool(15))
print(bool(3.14))
print(bool(0.0))
print(bool(1+2j))
print(bool(0+0j))
print(bool(-1))
print(bool(True))
print(bool(False))
#print(bool("vinay"))

"""33 reserve keyword"""

val1 = int(input("enter no. 1:"))#100
val2 = int(input("enter no. 2:"))#200
print("before swapping val1 =", val1, "val2 =", val2)
temp = val1 #temp = 100
val1 = val2 #val1 = 200
val2 = temp #val2 = 100
print("val1 =", val1, "val2 =", val2)

a = 100
b = 200
a1= a+b

b1= a1-b

a2= a1-b1
print(a1, b1, a2)

p1 = int(input("enter the mark of p1:"))
p2 = int(input("enter the mark of p2:"))
p3 = int(input("enter the mark of p3:"))
total = p1+p2+p3
per = total/3
print("total =", total)
print("persentage =", per)

pa = int(input("enter principal amount:"))
it = int(input("enter the intrest:"))
tm = int(input("enter the duration:"))
si = pa*it*tm/100
print("intrest",si)

h = int(input("enter height:"))
inch=h*12
cm = inch*2.54
print("inch =",inch, "cm =",cm)

num = 123 # 321
a= num % 10 #a=3
num = num // 10
b = num % 10
c = num // 10
rev = a*100+b*10+c*1
print(rev)

num = 123456
a= num % 10
print(a)
num = num//10
b = num % 10
print(b)
num = num//10
c = num % 10
print(c)
num = num//10
d = num % 10
print(d)
num = num//10
e = num % 10
print(e)
num = num//10
f = num % 10
print(f)
rev = a*100000+b*10000+c*1000+d*100+e*10+f*1
print(rev)

name = "help4code"
print("z"not in name)
print("z" in name)
print("p" in name)

#check positive nagitive & Zero
no=int(input("enter no:"))
if no>0:
    print("positive")
if no<0:
    print("nagitive")
if no==0:
    print("it is zero")

#chech the greater number
no1=int(input("enter no 1:"))
no2=int(input("enter no 2:"))
no3=int(input("enter no 3:"))
if no1>no2 and no1>no3:
  print("no1 is greater")
if no2>no3 and no2>no1:
  print("no2 is greater")
if no3>no1:
  print("no3 is greater")

n1=int(input("enter no 1:"))
n2=int(input("enter no 2:"))
n3=int(input("enter no 3:"))
n4=int(input("enter no 4:"))
n5=int(input("enter no 5:"))
if n1>n2 and n1>n3 and n1>n4 and n1>n5:
  print("n1 is greater")
if n2>n3 and n2>n4 and n2>n5 and n2>n1:
  print("n2 is greater")
if n3>n4 and n3>n5 and n3>n1 and n3>n2:
  print("n3 is greater")
if n4>n5 and n4>n1 and n4>n2 and n4>n3:
  print("n4 is greater")
if n5>n1 and n5>n2 and n5>n3 and n5>n4:
  print("n5 is greater")

username = input("enter username :")
passward = input("enter password :")
if username == passward:
  print("login success")
else:
  print("login failed")

#write a program to accept phy chem and math subjectmarks calculate total &  percentage and if percentage is grater then equal to 60 and gender is equal to male so hi is eligible for placement  else eligible for data entry job

phy=int(input("enter phy marks:"))
chem=int(input("enter chem marks:"))
math=int(input("enter math marks:"))
total=phy+chem+math
print(total)
per=total/3
print(per)
gender=input("enter gender m/f:")
if per>=60 and gender=="m":
  print("eligible for placement")
else:
  print("data entry job")

#write a program to accept value of A,B,C and find max value

a=int(input("enter a:"))
b=int(input("enter b:"))
c=int(input("enter c:"))
if a>b:
  if a>c:
    print("a is greater")
  else:
    print("c is greater")
else:
  if b>c:
    print("b is greater")
  else:
    print("c is greater")

#write a program if enter sundar it is holiday and enter other days print working day
day=input("enter day:")
if day=="sunday" or day=="saturday":
  print("it is weekend")
else:
  print("it is working day")

#write a program user enter any character print character user enter any symbol print synbol

ch = ord(input("enter character:"))
if ch>=65 and ch<=91:
  print("it is capital")
elif ch>=97 and ch<=122:
  print("it is lower case")
elif ch>=48 and ch<=57:
  print("it is number")
else:
  print("it is special character")
  print(ch)

am = int(input("enter amount for withdraw :"))
print("100 note", am//100)
print("50 note",(( am% 100)% 50)//50)
print("20 note",(( am% 100) %50) %20//20)
print("10 note", (((am% 100) % 50) % 20)//10)
print("5 note",(((( am% 100)%50) %20 )%5)//5)