# -*- coding: utf-8 -*-
"""DSA DAY 08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m2Oqv6758McFnhk-E9R85evDuWG3nK7g
"""

rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

matrix = []

print("Enter the matrix elements:")

for i in range(rows):
    row = list(map(int, input().split()))
    matrix.append(row)

print("Matrix is:")

for i in range(rows):
    for j in range(cols):
        print(matrix[i][j], end=" ")
    print()

n = int(input("Enter size of matrix: "))

matrix = []
a = []
for i in range(n):
    row = list(map(int, input(f"Enter row {i+1} elements: ").split()))
    matrix.append(row)

print("Matrix is:")
for row in matrix:
    print(row)
    a.append(max(row))

print("---------------------")
print(a)

import sys
class Node:
  def __init__(self,data):
    self.data = data
    self.next = None

class LinkedList:
  def addNode(self,value):
    Node = Node(value)
    if self.tail is None:
      self.tail = newNode

class linkedList:
  self.tail = Node

if __name__ == "__main__":
  object = LinkedList()
  while True:
    print("1. add node linkedlist :")
    print("2. add node in baginig :")
    print("3. add node in between :")
    print("4. add node in end :")
    print("5. display linked list :")
    print("6. exit")

    ch = int(input("enter ypur choice"))
    if ch == 1:
      value = int(input("enter data"))
      object.addNode(value)
      print("node added successfully insingle linkedlist")

import sys
class Node:
    def __init__(self,data):
        self.data = data
        self.next = None

class Linkedlist:
    def _init_(self):
        self.head = None
        self.tail = None

    def addNode(self,value):
        node = Node(value)
        if self.head is None:
            self.head = node
            self.tail = node
        else:
            self.tail.next = node
            self.tail = node

        def displaynode(self):
            print("------------------------")
            while self.head is not None:
                print(self.head.data,"|","===>",self.tail.data,end=" ")
                self.head=self.head.next
                print("------------------------")

        def addNodeBegin(self,value):
            node = Node(value)
            if self.head is None:
                self.head = node
                self.tail = node
            else:
                node.next = self.head
                self.head = node

#link list add,del,
if __name__ =='_main_':
    object = Linkedlist()

    while True:
        print("1. Add node linkedlist:")
        print("2. Add node in begining:")
        print("3. Add node in between:")
        print("4. Add node in end:")
        print("5. Display linkedlist:")
        print("exit")

        ch = int(input("Enter your choice:"))
        if ch == 1:
            value = int(input("enter value for node:"))
            object.addNode(value)
            print("node added successfully insingle linkedlist")

        elif ch == 5:
            object.Display()

        elif ch == 6:
            sys.exit()

        else:
            print("Invalid choice")

import sys

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class Linkedlist:
    def __init__(self):
        self.head = None
        self.tail = None

    def addNode(self, value):
        node = Node(value)
        if self.head is None:
            self.head = node
            self.tail = node
        else:
            self.tail.next = node
            self.tail = node

    def DisplayNode(self):
        print("------------------------")
        temp = self.head
        while temp is not None:
            print("|", temp.data, "|", "===>", end=" ")
            temp = temp.next
        print("None")
        print("------------------------")


# link list add,del,
if __name__ == '__main__':
    object = Linkedlist()

    while True:
        print("1. Add node linkedlist:")
        print("2. Add node in begining:")
        print("3. Add node in between:")
        print("4. Add node in end:")
        print("5. Display linkedlist:")
        print("6.exit")

        ch = int(input("Enter your choice:"))

        if ch == 1:
            value = int(input("enter value for node:"))
            object.addNode(value)
            print("node added successfully in single linkedlist")

        elif ch == 2:
            value = int(input("enter value for node:"))
            object.addNodeBegin(value)
            print("node added successfully in begining")

        elif ch == 3:
            value = int(input("enter value for node:"))
            index = int(input("enter position after that you have to insert"))
            object.addNodeBetween(index, value)
            print("node added successfully in between")

        elif ch == 4:
            value = int(input("enter value for node:"))
            object.addNodeEnd(value)
            print("node added successfully in end")

        elif ch == 5:
            object.DisplayNode()

        elif ch == 6:
            sys.exit()

        else:
            print("Invalid choice")

import sys

class Node:
    def __init__(self,data):
        self.data = data
        self.next = None

class Linkedlist:
    def __init__(self):
        self.head = None
        self.tail = None

    def addNode(self,value):
        node = Node(value)
        if self.head is None:
            self.head = node
            self.tail = node
        else:
            self.tail.next = node
            self.tail = node

    def addNodeBeggining(self,value):
        node = Node(value)
        if self.head is None:
            self.head = node
            self.tail = node
        else:
            node.next = self.head
            self.head = node

    def addNodeinBetween(self,index,value):
        node = Node(value)

        if self.head is None:
            self.head = node
            self.tail = node

        elif index == 0:
            node.next = self.head
            self.head = node

        else:
            temp = self.head
            for _ in range(index - 1):
                temp = temp.next

            node.next = temp.next
            temp.next = node

    def addNodeatEnd(self,value):
        node = Node(value)

        if self.head is None:
            self.head = node
            self.tail = node
        else:
            self.tail.next = node
            self.tail = node

    def displayNode(self):
        print("------------------------")
        temp = self.head
        while temp is not None:
            print("|",temp.data,"|","===>",end=" ")
            temp = temp.next
        print("None")
        print("------------------------")

    def deleteNode(self,value):
    temp = self.head
    prev = None

    if temp is not None and temp.data == value:
        self.head = temp.next
        temp = None
        return

    while temp is not None:
        if temp.data == value:
            break
        prev = temp
        temp = temp.next

    if temp is None:
        print("Value not found")
        return

    prev.next = temp.next
    temp = None



# link list add,del
if __name__ == '__main__':
    object = Linkedlist()

    while True:
        print("1. Add node linkedlist:")
        print("2. Add node in begining:")
        print("3. Add node in between:")
        print("4. Add node in end:")
        print("5. Display linkedlist:")
        print("6. delete a node ")
        print("7.exit")

        ch = int(input("Enter your choice:"))

        if ch == 1:
            value = int(input("enter value for node:"))
            object.addNode(value)
            print("node added successfully in single linkedlist")

        elif ch == 2:
            value = int(input("enter value for node:"))
            object.addNodeBeggining(value)
            print("node added successfully in single linkedlist")

        elif ch == 3:
            value = int(input("enter value for node:"))
            index = int(input("enter position after that you have to insert: "))
            object.addNodeinBetween(index,value)
            print("node added successfully in single linkedlist")

        elif ch == 4:
            value = int(input("enter value for node:"))
            object.addNodeatEnd(value)
            print("node added successfully in single linkedlist")

        elif ch == 5:
            object.displayNode()

        elif ch == 6:
            value = int(input("enter value for node:"))
            object.deleteNode(value)
            print("node deleted successfully in single linkedlist")

        elif ch == 7:
            sys.exit()

        else:
            print("Invalid choice")

import sys

class Node:
    def __init__(self,data):
        self.data = data
        self.next = None

class Linkedlist:
    def __init__(self):
        self.head = None
        self.tail = None

    def addNode(self,value):
        node = Node(value)
        if self.head is None:
            self.head = node
            self.tail = node
        else:
            self.tail.next = node
            self.tail = node

    def addNodeBeggining(self,value):
        node = Node(value)
        if self.head is None:
            self.head = node
            self.tail = node
        else:
            node.next = self.head
            self.head = node

    def addNodeinBetween(self,index,value):
        node = Node(value)

        if self.head is None:
            self.head = node
            self.tail = node

        elif index == 0:
            node.next = self.head
            self.head = node

        else:
            temp = self.head
            for _ in range(index - 1):
                temp = temp.next

            node.next = temp.next
            temp.next = node

    def addNodeatEnd(self,value):
        node = Node(value)

        if self.head is None:
            self.head = node
            self.tail = node
        else:
            self.tail.next = node
            self.tail = node

    def displayNode(self):
        print("------------------------")
        temp = self.head
        while temp is not None:
            print("|",temp.data,"|","===>",end=" ")
            temp = temp.next
        print("None")
        print("------------------------")

    def deleteNode(self,value):
        temp = self.head
        prev = None

        if temp is not None and temp.data == value:
            self.head = temp.next
            return

        while temp is not None:
            if temp.data == value:
                break
            prev = temp
            temp = temp.next

        if temp is None:
            print("Value not found")
            return

        prev.next = temp.next


# link list add,del
if __name__ == '__main__':
    object = Linkedlist()

    while True:
        print("1. Add node linkedlist:")
        print("2. Add node in begining:")
        print("3. Add node in between:")
        print("4. Add node in end:")
        print("5. Display linkedlist:")
        print("6. delete a node ")
        print("7.exit")

        ch = int(input("Enter your choice:"))

        if ch == 1:
            value = int(input("enter value for node:"))
            object.addNode(value)
            print("node added successfully in single linkedlist")

        elif ch == 2:
            value = int(input("enter value for node:"))
            object.addNodeBeggining(value)
            print("node added successfully in single linkedlist")

        elif ch == 3:
            value = int(input("enter value for node:"))
            index = int(input("enter position after that you have to insert: "))
            object.addNodeinBetween(index,value)
            print("node added successfully in single linkedlist")

        elif ch == 4:
            value = int(input("enter value for node:"))
            object.addNodeatEnd(value)
            print("node added successfully")

        elif ch == 5:
            object.displayNode()

        elif ch == 6:
            value = int(input("enter value for node:"))
            object.deleteNode(value)
            print("node deleted successfully")

        elif ch == 7:
            sys.exit()

        else:
            print("Invalid choice")

#ip = [0, 0, 1, 2, 0, 3, 0, 4]

#while ip and ip[0] == 0:
  #  ip.pop(0)

ip = [0, 0, 1, 2, 0, 3, 0, 4]

while ip and ip[0] == 0:
    ip.pop(0)

print(ip)

"""recursion"""

from ast import pattern
import re
count = 0
pattern = re.compile("function")

matcher = pattern.finditer("a function in python is definded by def st")
for i in matcher:
    count += 1
    print(i.start(),"....",i.end(),"....",i.group())
print("the number of occurrences : ",count)

from ast import pattern
import re
count = 0
matcher = re.finditer("HI","HIHIHIHIHI")

#matcher = pattern.finditer("a function in python is definded by def st")
for i in matcher:
    count += 1
    print(i.start(),"....",i.end(),"....",i.group())
print("the number of occurrences : ",count)

from ast import pattern
import re
obj = input("enter any character")
objmatch = re.finditer(obj, "a75b @k9z")
for match in objmatch:
    print(match.start(),"....",match.end(),"....",match.group())

import re
a = input("enter starting to perform match operation :")
mtch = re.match(a,"python is very important language")
print(mtch)
if mtch !=None:
  print("match found at beginning level")
  print(mtch.start()," ",mtch.end())
else:
  print("there is no matching at begining level")

"""match() function

fullmatch()
as a name suggest when we have to match full string with the given pattern then we have to use fullmatch() function.
"""

import re
a = input("enter starting to perform match operation :")
mtch = re.fullmatch(a,"pythonisvery")
print(mtch)
if mtch !=None:
  print("match found at beginning level")
  print(mtch.start()," ",mtch.end())
else:
  print("there is no matching at begining level")

"""search() function

if the match found anywhere in the string then it return object else it
"""

import re
a = input("enter starting to perform match operation :")
mtch = re.search(a,"python sss dynamic lannn")
print(mtch)
if mtch !=None:
  print("match found at beginning level")
  print(mtch.start()," ",mtch.end())
else:
  print("there is no matching at begining level")

import re
a = input("enter starting to perform match operation :")
f = open('myfile.txt','r')
c = f.read()
mtch = re.search(a,c)
print(mtch)
if mtch !=None:
  print("match found at beginning level")
  print(mtch.start()," ",mtch.end())
else:
  print("there is no matching at begining level")

"""findall() function

this function return a list which containing all matches.
"""

import re
mtch = re.findall('[0-9]',"asdf456!@#72$*")
print(mtch)

"""sub() function:

this function preform substitution or replacement
"""

import re
obj = re.sub('[a-zA-Z]','X','qwej asdf ASDF 1234')
print(obj)

"""subn() function

it is as similar as sub() function only one thing is diffierent that it also return number of replacement. this return in tuple where first element is string and second  one is number of replacement.
"""

import re
obj = re.subn('[0-7]','@','asd987tr234@#$')
print(obj)
print("the string is = ",obj[0])
print("the number of replacement is = ",obj[1])

import re
no = input("enter mobile number")
obj =re.fullmatch("[0-5]\d(9)",no)
if obj != None:
  print("valid mobile number")
else:
  print("invalid mobile number")

import re
s = input("Enter email id: ")
m = re.fullmatch("\w[a-zA-Z0-9_.]*@gmail[.]com",s)
if m != None:
    print("valid email id")
else:
    print("invalid email id")# "\w[a-zA-Z0-9_.]*@ybit[.]ac[.]in"

import re
s = input("Enter email id: ")
m = re.fullmatch("\w[a-zA-Z0-9_.]*@ybit[.]ac[.]in",s)
if m != None:
    print("valid email id")
else:
    print("invalid email id")

import os,sys
fname = input("enter file name :")
if os.path.isfile(fname):
  print("file exist: ", fname)
  f=open(fname,"r")
else:
  print("file does not exit : ",fname)
  sys.exit(0)
print("the content of file is:")
data =f.read()
print(data)