# -*- coding: utf-8 -*-
"""DSA DAY07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R4EK9OqoIM4SUuwbgyAYwQknoFog3adL
"""

#sort dictionary by key or value
ip= {"A":1,"B":2,"C":3}
#op ={c,b,a}
sorted_dict = dict(sorted(ip.items(),reverse=True))
print(sorted_dict)





#remove all element from dict
ip = {"A":1,"B":2,"C":3}
a = ip.clear()
print(a)

ip= {"A":1,"B":2,"C":3}
#op ={c,b,a}
desc = dict(sorted(ip.items(),reverse=True))
asc = dict(sorted(ip.items()))
print(asc)
print(desc)

#sort dictionary by key or value
ip= {"A":1,"B":2,"C":3}
#op ={c,b,a}
desc = dict(sorted(ip.items(),reverse=True))
asc = dict(sorted(ip.items()))
print(asc)
print(desc)


#remove all element from dict
ip = {"A":1,"B":2,"C":3}
a = ip.clear()
print(ip)

import sys
class Queue:

  def __init__(self, queueSize):   # corrected constructor
    self.queueList = []
    self.queueSize = queueSize

  def isFull(self):
      if len(self.queueList) == self.queueSize:
          return True
      else:
          return False

  def Enqueue(self, value):
    if self.isFull():
      print("Queue is full")
    else:
      self.queueList.append(value)
      print(self.queueList)

  def displayQueue(self):
    print("------------------")
    print(self.queueList)
    print("------------------")

  def isEmpty(self):
      if self.queueList == []:
          return True
      else:
          return False

  def Dequeue(self):
      if self.isEmpty():
          return "Queue is empty"
      else:
          return self.queueList.pop(0)

  def deleteQueue(self):
      self.queueList = None
      return "Queue is deleted"

  def peek(self):
      if self.isEmpty():
          return "Queue is empty"
      else:
          return self.queueList[0]


size = int(input("enter the size of queue : "))
queueObj = Queue(size)

while True:

  print("---------------------------")
  print("1. enqueue element in queue")
  print("2. display queue element")
  print("3. check queue isempty")
  print("4. dequeue operation")
  print("5. delete queue")
  print("6. peek operation")
  print("7. Enter new queue size: ")
  print("8. Exit")
  print("---------------------------")

  choice = int(input("enter your choice : "))

  if choice == 1:
    val = int(input("enter value for queue : "))
    queueObj.Enqueue(val)

  elif choice == 2:
    queueObj.displayQueue()

  elif choice == 3:
    print(queueObj.isEmpty())

  elif choice == 4:
    print(queueObj.Dequeue())

  elif choice == 5:
    print(queueObj.deleteQueue())

  elif choice == 6:
    print(queueObj.peek())

  elif choice == 7:
        size = int(input("Enter new queue size: "))
        queueobj = Queue(size)
        print("New queue created!")

  elif choice == 8:
    sys.exit()

def findlargestnumber():
    firstvalue = array[0]# first value = 5        o(1)
    for i in range(1,len(array)): # i =2 O[i]     o(n)
        if array[i] > firstvalue: # 5>4 ==>       o(1)
            firstvalue = array[i]
    return firstvalue

array = [1,4,5,6,7,1,9,3,4,5,6]
print(findlargestnumber())

def countSpecialCharacters(string):
    special_characters = "!@#$%^&*()_+-=~`|\\:;\"'<>,.?/"
    count = 0
    for char in string:
        if char in special_characters:
            count += 1
    return count

string = "gagg54@#vscad!s'"
print(countSpecialCharacters(string))

ip = "gagg54@#vscad!s'"
count = 0
for i in ip:
    if not i.isalnum():
        count+=1
print(count)

import math

size = int(input("Enter the number of elements: "))
a = []

for i in range(size):
    element = int(input(f"Enter element {i+1}: "))
    a.append(element)

print("The elements are:", a)

# Store square roots in a new list
sqrt_list = []

for i in a:
    sqrt_list.append(math.sqrt(i))

print("Square roots:", sqrt_list)
print("Length:", len(sqrt_list))

var = "gagg54@#vscad!s'"
count = 0
for i in var:
  z =ard(i)
  if z>=97 and z<=122:
    count+=1
print(count)

def linearSearch(array,target):  #======>O(1)
    for i in range (len(array)):  #=====>O(1)
        if array[i] == target:  #=======>O(1)
            return i  #=================>O(1)
    return -1  #========================>O(1)



array =[1,2,3,4,5,6,7,8,9]
target = 4
result=linearSearch(array, target)
if result == -1:
    print("not found")
else:
    print('Element found at index no=',result)

def binarySearch(array,target):
    start = 0
    end = len(array)-1
    while start <= end:
        mid = (start+end) //2
        if array[mid] == target:
            return mid
        elif array[mid]< target:
            start = mid+1
        else:
            end = mid -1
    return -1
                                     #o(1)

sorted_array =[1,2,3,4,5,6,7,8,9]
target = 44
result=binarySearch(sorted_array, target)
if result == -1:
    print("not found")
else:
    print('Element found at index no=',result)

class Node:
  def __init__(self, data):
    self.data = data
    self.next = None

class LinkedList:
  def __init__(self):
    self.head = None

linkedList = LinkedList()
linkedList.head = Node(5) #first node

second = Node(10)
third = Node(15)
fourth = Node(20)

linkedList.head.next = second
second.next = third
third.next = fourth

print(fourth.next)
print(third.next)
print(second.next)

while linkedList.head != None:
  print("|",linkedList.head.data,"|",linkedList.head.data,"|")
  linkedList.head = linkedList.head.next

import sys
class Node:
  def __init__(self,data):
    self.data = data
    self.next = None

class LinkedList:
  def __init__(self):
    self.head = None
    self.tail = None

class linkedList:
  self.tail = Node

if __name__ == "__main__":
  object = LinkedList()
  while True:
    print("1. add node linkedlist :")
    print("2. add node in baginig :")
    print("3. add node in between :")
    print("4. add node in end :")
    print("5. display linked list :")
    print("6. exit")

    ch = int(input("enter ypur choice"))
    if ch == 1:
      value = int(input("enter data"))
      object.addNode(value)
      print("node added successfully insingle linkedlist")