# -*- coding: utf-8 -*-
"""DSA DAY02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIVmJTZeoILs7OBP3iIMKv1kf9WWDNXm
"""

name = "prashantjha"
#indexing = 012345678910

print(name[0])
print(name[1])
print(name[-1])
print(name[0:5])
#print(name[15])
print(name[1:])
print(name[:5])
print(name[1:8:2])
print(name[:])
print(name[::-1])

s = "Python is a High level programming Language"

print(s.lower())
print(s.upper())
print(s.swapcase())
print(s.title())
print(s.capitalize())

print("Subject marks:")
phy = 50
chem = 60
math = 70
print("phy = {} chem = {} math = {}" .format(phy,chem,math))
print("phy = {0} chem = {1} math = {2}" .format(phy,chem,math))
print("phy = {x} chem = {y} math = {z}" .format(x=phy,y=chem,z=math))
t = phy+chem+math
print("total marks ",f"{t}")
print("roll no.","7".zfill(4))

#looping
#for (initialization; condition; increament/decrement)
for i in range(1,11):
    print(i)

for i in range(1,11):
    print(i*2)

for i in range(1,11):
    print(i*1,"       ",i*2,"      ",i*3,"   ",i*4,"    ",i*5,"   ",i*6,"    ",i*7,"   ",i*8,"    ",i*9,"         ",i*10)

print()

for i in range(1,11):
    print(i*11,"      ",i*12,"   ",i*13,"    ",i*14,"   ",i*15,"    ",i*16,"   ",i*17,"    ",i*18,"         ",i*19, "    ",i*20)

name="racear"
for i in name:
  print(i)

# WTP to remove duplicate using loop
name = "racear"
newname=""
for i in name:
  if i not in newname:
    newname +=i
print(newname)

for i in range(10,0,-2):
  print(i)

name = "mumbai"
n=len(name)
print(n)
print()
# WAP reverse a string
for i in name[::-1]:
  print(i)

print(name[::-1])

name = "mumbai"
newname = " "
n = len(name)
for i in range(n-1, -1,-1):
  newname+=name[i]
print(newname)

#wap to check string is palindrom or not
name = "madam"
#print(name)
#print(name[::-1])
if name==name[::-1]:
  print("it is palindrom")
else:
  print("it is not palindrom")

#mylist = ["prashant", "ashish", "komal", "ankush","ashish", 77, "sandeep", 60.52, "prashant"]

#print(mylist)
#print(type(mylist))
#print(mylist[2])
#print(mylist[-2])
#print(mylist[:5])
#print(mylist[1:])
#print(mylist[1:8:3])
#print(mylist[:])
#print(mylist[::-1])
print()
#mylist[2]="akshay"
print(mylist)
print()

if "ankush" in mylist:
  print("yes it is available")
else:
  print("no")
print()
mylist.append("harsh")
mylist.append("laxman")
print(mylist)
print()
mylist.insert(1,"sanket")
print(mylist)
print()
mylist.remove("sandeep")
print(mylist)
print()
print()
print()
newlist = mylist.copy()
print(newlist)

#nylist = [["prashant", "jha"],[85.56],[440022, "yyy"]]
print("exm of multidimentional lest : ")
print(nylist)
#print(nylist[row][col])
print(nylist[0][0])
print(nylist[0][1])
print(nylist[1][0])
print(nylist[2][0])
print(nylist[2][1])
print()
#print(nylist[1][1])
print()
list1=["prashant", "jha"]
print(list1*2)
print()
list2 = [50,25,50]
print(list1+list2)

arr=[[1,2,3,4],
     [4,5,6,7,],
     [8,9,10,11],
     [12,13,14,15]]
for i in range(0,4):
  print(arr[i].pop())