# -*- coding: utf-8 -*-
"""DSA DAY 06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ne3KH-qvwA4NDKiaaCZYwlO2wyM-xmFi
"""

astring = "aaabbbccc"
newstring = ""
count = 1

for i in range(len(astring)):
    if i < len(astring) - 1 and astring[i] == astring[i+1]:
        count += 1
    else:
        newstring += str(count) + astring[i]
        count = 1

print(newstring)

a = "hello world"
list = a.split()
new_list = []
for item in list:
    new_list.append(item[::-1])
print(" ".join(new_list))

from abc import ABC, abstractmethod
class help4code(ABC):
    @abstractmethod #decorator
    def training(self):
        pass

    @abstractmethod
    def placement(self):
        pass

class Ashish(help4code):
    def training(self):
        print("c, c++, java")
    def placement(self):
        print("java placement")

class Ankush(help4code):
    def training(self):
        print("Python, Django")
    def placement(self):
        print("python placement student")

class Prashant(help4code):
    def training(self):
        print("machine learning")
    def placement(self):
        print("Data science placement")

obj1 = Ashish()
obj2 = Ankush()
obj3 = Prashant()

obj1.training()
obj1.placement()
obj2.training()
obj2.placement()
obj3.training()
obj3.placement()

from abc import ABC, abstractmethod
class Irctc(ABC):

  @abstractmethod
  def bookTicket(self):
    pass

class MakeMyTrip(Irctc):
  def bookTicket(self):
    print("========================")
    print("welcom to MakeMyTrip.com")
    source = input("enter a source station name")
    dest = input("enter a distination station name")
    data = input("enter data")
    print("========================")

class GoIbibo(Irctc):
  def bookTicket(self):
    print("welcome to GoIbibo.com")
    source = input("enter a source station name")
    dest = input("enter a distination station name")
    data = input("enter data")
    print("========================")

class Yatra(Irctc):
  def bookTicket(self):
    print("welcome to Yatra.com")
    source = input("enter a source station name")
    dest = input("enter a distination station name")
    data = input("enter data")
    print("========================")

obj1 = MakeMyTrip()
obj2 = GoIbibo()
obj3 = Yatra()
obj1.bookTicket()
obj2.bookTicket()
obj3.bookTicket()

class Base:
  def __init__(self):
    print("parent class constructor called")
    self.a = "prashant" #public data menber
    #self.__c = "ashish" #private data member

class Derived(Base):
  def __init__ (self):
    Base.__init__(self)
    #print(" calling private member of base class")
    #print(self.a)
    #print(self.__c)

#obj1 = Derived()
#print(obj1.a)
#print(obj1.__c)
obj2 = Base()
print(obj2.a)
#print(obj2.__c)

class Rbi:
  #declaration public method
  def publicPolicy(self):
    print("check the public policy of Rbi")

#declaration private method
  def privatePolicy(self):
    print("there is some private policy which is not accessible for public")

class Sbi(Rbi):
  def __init__(self):
    Rbi.__init__(self)

  def callingPolicyMethod(self):
    print("\nInside child class")
    self.publicPolicy()

  def callingPrivatePolicy(self):
    self.privatePolicy()

obj1 = Sbi()
#obj1.callingPolicyMethod()
#obj1.callingPrivatePolicy()
#obj1.publicPolicy()
#obj1._privatePolicy()
#obj2 = Rbi()
#obj2.publicPolicy()
#obj2._privatePolicy()
obj2 = Rbi()
obj2.publicPolicy()
obj2._Rbi_publicPolicy()

#write a program to place the all even no. before the all the odd no.
list = [10,98,3,33,12,22,21,11]

"""1. stack implemention without size limit
2. stack implementatiom with size limit

1. push
2. pop

stack implementation with size limit
"""

import sys
class Stack:
  def __init__(self):
    self.stacklist = [] #stack created

  def push(self, value):
    self.stacklist.append(value)
    print(self.stacklist)

  def displaystack(self):
    print(self.stacklist)

  def isEmpty(self):
    if len(self.stacklist) == 0:
      return True
    else:
      return False

  def pop(self):
    if self.isEmpty():
      print("stack is empty")
    else:
      self.stacklist.pop()
      print(self.stacklist)

  def deleteStack(self):
    self.stacklist = None
    return "stack is deleted"

  def peek(self):
    if self.isEmpty():
      print("stack is empty")
    else:
      return self.stacklist[-1]

stackobj = Stack()

while True:

  print("1. push element in stack :")
  print("2. display stack element")
  print("3. check isempty")
  print("4. pop element from stack")
  print("5. delete stack")
  print("6. peek opration")
  print("7. exit")


  choice = int(input("enter your choice : "))
  if choice ==1:
    val = int(input("enter value for stack"))
    stackobj.push(val)
  elif choice == 2:
    stackobj.displaystack()
  elif choice == 3:
    print(stackobj.isEmpty())
  elif choice == 4:
    print(stackobj.pop())
  elif choice == 5:
    print(stackobj.deleteStack())
  elif choice == 6:
    print(stackobj.peek())
  elif choice == 7:
    sys.exit()

  else:
    break

"""stack implementation with size limit"""

import sys
class Stack:
  def __init__(self, stackSize): #paramerize constructor
    self.stacklist = [] #stack created
    self.stackSize = stackSize

  def isFull(self):
    if len(self.stacklist) == self.stackSize:
      return True
    else:
      return False

  def push(self, value):
    self.stacklist.append(value)
    print(self.stacklist)

  def displaystack(self):
    print(self.stacklist)

  def isEmpty(self):
    if len(self.stacklist) == 0:
      return True
    else:
      return False

  def pop(self):
    if self.isEmpty():
      print("stack is empty")
    else:
      self.stacklist.pop()
      print(self.stacklist)

  def deleteStack(self):
    self.stacklist = None
    return "stack is deleted"

  def peek(self):
    if self.isEmpty():
      print("stack is empty")
    else:
      return self.stacklist[-1]

size = int(input("enter size of stack"))
stackobj = Stack(size)

stackobj = Stack()

while True:

  print("1. push element in stack :")
  print("2. display stack element")
  print("3. check isempty")
  print("4. pop element from stack")
  print("5. delete stack")
  print("6. peek opration")
  print("7. exit")


  choice = int(input("enter your choice : "))
  if choice ==1:
    val = int(input("enter value for stack"))
    stackobj.push(val)
  elif choice == 2:
    stackobj.displaystack()
  elif choice == 3:
    print(stackobj.isEmpty())
  elif choice == 4:
    print(stackobj.pop())
  elif choice == 5:
    print(stackobj.deleteStack())
  elif choice == 6:
    print(stackobj.peek())
  elif choice == 7:
    sys.exit()

  else:
    break

import sys
class Stack:
  def __init__(self, stackSize): #paramerize constructor
    self.stacklist = [] #stack created
    self.stackSize = stackSize

  def isFull(self):
    if len(self.stacklist) == self.stackSize:
      return True
    else:
      return False

  def push(self, value):
    if self.isFull():
      print("stack is full")
    else:
      self.stacklist.append(value)
      print(self.stacklist)

  def displaystack(self):
    print(self.stacklist)

  def isEmpty(self):
    if len(self.stacklist) == 0:
      return True
    else:
      return False

  def pop(self):
    if self.isEmpty():
      print("stack is empty")
    else:
      self.stacklist.pop()
      print(self.stacklist)

  def deleteStack(self):
    self.stacklist = None
    return "stack is deleted"

  def peek(self):
    if self.isEmpty():
      print("stack is empty")
    else:
      return self.stacklist[-1]

size = int(input("enter size of stack"))
stackobj = Stack(size)

stackobj = Stack(size)

while True:

  print("1. push element in stack :")
  print("2. display stack element")
  print("3. check isempty")
  print("4. pop element from stack")
  print("5. delete stack")
  print("6. peek opration")
  print("7. exit")


  choice = int(input("enter your choice : "))
  if choice ==1:
    val = int(input("enter value for stack"))
    stackobj.push(val)
  elif choice == 2:
    stackobj.displaystack()
  elif choice == 3:
    print(stackobj.isEmpty())
  elif choice == 4:
    print(stackobj.pop())
  elif choice == 5:
    print(stackobj.deleteStack())
  elif choice == 6:
    print(stackobj.peek())
  elif choice == 7:
    sys.exit()

  else:
    break

def tower_of_hanoi(n, source, middle, destination):
    if n == 1:
        print(f"Move disk 1 from {source} to {destination}")
        return


    tower_of_hanoi(n-1, source, destination, middle)


    print(f"Move disk {n} from {source} to {destination}")


    tower_of_hanoi(n-1, middle, source, destination)



n = 3

tower_of_hanoi(n, 'A', 'B', 'C')

import time
class tower:
    def _init_(self):
        print("welcome to tower of hanoi game")
        print()
        print("given problem A=[3,2,1]     B=[]    c[]  ")
        print()
        print("expected output")

class Tower:
    def tower(self,item):
        self.A.append(item)
        time.sleep()
        print("A:",self.A)
        print("items in tower A \n")

    def pass1(self):
        self.temp = self.A.pop(2)
        self.C.append(self.temp)
        time.sleep(3)
        print("A :",self.A   ,"  ","B :",self.B  ,"  ","C :",self.C)
        print("Pass one completed..............\n")

    def pass2(self):
        self.temp = self.A.pop(2)
        self.B.append(self.temp)
        time.sleep(3)
        print("A :",self.A   ,"  ","B :",self.B  ,"  ","C :",self.C)
        print("Pass two completed..............\n")

    def pass3(self):
        self.temp = self.A.pop(0)
        self.B.append(self.temp)
        time.sleep(3)
        print("A :",self.A   ,"  ","B :",self.B  ,"  ","C :",self.C)
        print("Pass two completed..............\n")