# -*- coding: utf-8 -*-
"""DSA DAY2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Bom3kMv5jAwCMsrto9GA5sHo_VFKEPb
"""

arr=[[1,2,3,4],
     [4,5,6,7,],
     [8,9,10,11],
     [12,13,14,15]]
for i in range(0,4):
  print(arr[i].pop())

arr = [1,2,3,4,5,6]
for i in range(1,6):
  arr[i - 1]=arr[i]
for i in range(0,6):
  print(arr[i], end = "")

a=[1,2,3,4,5,6,7,8,9]
a[::2]=10,20,30,40,50,60
print(a)

a=[1,2,3,4,5]
print(a[3:0:-1])

mytuple=("prashant","ashish","rahul","sandeep","komal",23, 3.15, "rajesh")
print(mytuple)
print(type(mytuple))

#mytuple[2]="sunil"
print(mytuple)

init_tuple=() #tuple assign 0 value difault
print(init_tuple.__len__())

init_tuple_a = 'a','b'
init_tuple_b = ('a','b')
print(id(init_tuple_a))
print(id(init_tuple_b))
print(init_tuple_a == init_tuple_b)

init_tuple_a = '1','2'
init_tuple_b = ('3','4')
print(init_tuple_a + init_tuple_b)

init_tuple = ('python',)*3
print(type(init_tuple))

init_tuple =(1,)*3
init_tuple[0] = 2
print(init_tuple)

init_tuple = ((1,2),)*7
print(init_tuple)
print(len(init_tuple[3:8]))

name =[4,2,5,6,8,2]
for i in name:
  print(i)

a = [4,0,2,5,0,1]   #output a=[4,2,5,1,0,0]
for i in a:
  if i==0:
    a.remove(i)
    a.append(i)
print(a)

a= [1,2,2,3,4,4,5]  # output a=[1,2,3,4,5]
b=[]
for i in a:
  if i not in b:
    b.append(i)
print(b)

a =[1,2,3]
b =[2,3,4]
c =[3,4,5] #output [3] common element
for i in a:
  if i in b and i in c:
    print(i)

n = int(input("enter the number"))
arr=[]
for i in range(n):
  val =int(input("enter the value"))
  arr.append(val)
sum=0
print(arr)
for i in range(n):
  if i+1 in range(n):
    sum+=abs(arr[i]-arr[i+1])
print(sum)

for i in range(1,5):
  if i==3:
    break
  print(i)

print()
for i in range(1,5):
  if i==3:
    continue
  print(i)

# output 1,2,3,4,5 5,4,3,2,1
for i,j in zip(range(1,6),range(5,0,-1)):
  if i==1 and j==6:
    continue
  print(i," ",j)

a = "prashant*is*a*good*programmer"
s=a.split("*")
s1="".join(s)
print(s1)
print("*"*a.count("*")+s1)

a = "prashant*is*a*good*programmer"
new=' '
val=' '
for i in a:
  if i !='*':
    new += i
  else:
    val+=i
print(new)
print(str(val+new))

a =50
b=30
c=20
d=10
print((a+b)*c/d)
print((a-b)*(c/d))
print(a+(b*c)/d)

x=['A','B','C']
y=['A','B','C']
z=[1,2,3,4]
print(x==y)
print(x==z)
print(x!=z)
print(id(x==y))
print(id(x==z))
print(id(x!=z))

#check for anagrams #input= listen and silent
a ="listen"
b ="silent"
if sorted(a) == sorted(b):
  print("anagrams")
else:
  print("not anagrams")

#write a program count a words in a string
a="this is a sentence"
count = 1
for i in a:
  if i == " ":
    count += 1
print(count)

#input = [1,2,3,4]
#output = [24,12,8,6]

a=[1,2,3,4]
b=[1,1,1,1]
for i in range(len(a)):
  for j in range(len(a)):
    if i !=j:
      b[i]*=a[j]
print(b)