# -*- coding: utf-8 -*-
"""DSA DAY05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s8HiPJqHqJZak2P6vxDIdcx09PJCkHuL
"""

#revere a list
a=[1,2,3,4,5]
a.reverse()
print(a)

a=[1,2,3,2,1]

if a==a[::-1]:
  print("it is palindrom")
else:
  print("it is not palindrom")

#find commen element in two list
a=[1,2,3,4]
b=[3,4,5,6]
newlist =[]
for i in a:
  if i in b:
    newlist.append(i)
print(newlist)

class Student:  #class name always capital
  roll_no = 101

  def StudentData(self): #mwthod
    print("student info")

obj = Student()
obj.StudentData()
print(obj.roll_no)

class Demo:
  def __init__(self):
    print("I am constructor")

  def msg(self):
    print("hello class")

obj = Demo()
print(obj)
obj1=Demo()
obj.msg()

class Hod:
  def __init__(self):
    self.name="prashant jha"
    self.age=53
    self.empid=1001
  def info(self):
    print("my name is",self.name)
    print("my age is",self.age)
    print("my empid is",self.empid)
obj = Hod()
obj.info()

class Hod:
  def __init__(self,name,age,roll_no): #parametrize constructor
    self.name=name
    self.age=age
    self.roll_no=roll_no

  def show(self):
    print("my name is",self.name)
    print("my age is",self.age)
    print("my roll_no is",self.roll_no)

obj = Hod("arjun",53,1001)
obj.show()

class New:
  def __init__(self):
    self.a =10
obj1 =New()
obj2 =New()
obj3 =New()
print(obj1.a)
print(obj2.a)
print(obj3.a)
obj1.a = 20
print()
print(obj1.a)
print(obj2.a)
print(obj3.a)

class Student:
  def __init__(self):
    self.name="prashant jha"
    self.roll_no=1001

  def getdata(self):
    self.s_mob = 123456789

obj =Student()
obj.getdata()
del obj.s_mob
obj.s_branch = "cs"
print(obj.__dict__)

class New:
  a = 10
  def __init__(self):
    self.name="prashant jha"
obj1 = New()
obj2 = New()
obj3 = New()
print(obj1.a)
print(obj2.a)
print(obj3.a)
New.a=50
print(obj1.a)
print(obj2.a)
print(obj3.a)

#crud program
import sys

class CRUD:
  def __init__(self):
    print("student management system")
    self.studentId = {}
    self.studentName = {}
    self.studentRollno = {}
    self.studentCity = {}

  def addStudent(self):
    self.studentId.append(int(input("enter student ID :")))
    self.studentId.append(input("enter student ID :"))
    self.studentName.append(input("enter student name :"))
    self.studentRollno.append(input("enter student rollno :"))
    self.studentCity.append(input("enter student city"))
    print("student added successfully")

  def disply(self):
    print(self.studentId, "studentID")
    print(self.studentName, "studentName")
    print(self.studentRollno, "studentRollno")
    print(self.studentCity, "studentCity")

obj = CRUD()
while True:
    print("\n1.add student")
    print("2.display student")
    print("3.exit")
    choice = int(input("enter your choice :"))
    if choice == 1:
      obj.addStudent()
    elif choice == 2:
      obj.display()
    elif choice == 3:
      sys.exit()
    else:
      print("invalid choice")

import sys

class CRUD:
  def __init__(self):
    print("Student Management System")
    self.studentId = []
    self.studentName = []
    self.studentRollno = []
    self.studentCity = []

  def addStudent(self):
    self.studentId.append(int(input("Enter student ID: ")))
    self.studentName.append(input("Enter student name: "))
    self.studentRollno.append(input("Enter student rollno: "))
    self.studentCity.append(input("Enter student city: "))
    print("Student added successfully")

  def display(self):
    print("Student IDs:", self.studentId)
    print("Student Names:", self.studentName)
    print("Student Rollnos:", self.studentRollno)
    print("Student Cities:", self.studentCity)


obj = CRUD()

while True:
    print("\n1. Add Student")
    print("2. Display Student")
    print("3. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        obj.addStudent()
    elif choice == 2:
        obj.display()
    elif choice == 3:
      print("exiting.....")
      sys.exit()
    else:
        print("Invalid choice")

class Std:
  def __init__(self,name, rollno, mob):
    self.name=name
    self.rollno=rollno
    self.mob=mob

  def display(self):
    print(self.name," ", self.rollno ," ", self.mob," ")

stud = Std("prashant",1001,123456789)
stud.display()

class Student:
  @staticmethod
  def get_personal_detail(firstname,lastname):
    print("your persnal detail :",firstname,lastname)

  @staticmethod
  def contect_detail(firstname,lastname):
    print("your contact detail :",firstname,lastname)

Student.get_personal_detail("prashant","jha")
Student.contect_detail(123456789,1001)

"""extending property from one class to another class is called inheritance.
directly, we are getting here reusability concept
-> base class = a class which inherit its property to another is called base class or parent class
-> deriver class
"""

class Clg:
  def college_name(self):
    print("modern college")

class Student(Clg):
  def student_info(self):
    print("name : prashant jha")
    print("branch : cs")

obj = Student()
obj.college_name()
obj.student_info()

class Clg:
  def college_name(self):
    print("modern college")

class Std(Clg):
  def student_info(self):
    print("name : prashant jha")
    print("branch : cs")

class Exam(Std):
  def subject(self):
    print("subject1 : design engineering")
    print("subject2 : math")
    print("subject2 : c-language")

obj = Exam()
obj.college_name()
obj.student_info()
obj.subject()

class SubMark:
  math = int(input("enter math mark :"))
  DE = int(input("enter DE mark :"))
  C = int(input("enter C mark :"))
  english =int(input("enter english mark :"))

class PracMarks:
  cpract = int(input("enter marks of c:"))

class Result(SubMark, PracMarks):
  def total(self):
    if self.math>=40 and self.DE>=40 and self.c>=40 and self.english>=40 and self.cpract>=20:
      print("pass")
    else:
      print("fail")

obj = Result()
obj.total()

class Princ:
  def role(self):
    print("principle= i am managing all acivity of college")

class Dean:
  def role(self):
    print("dean= i am decision talking person")

class Hod:
  def role(self):
    print("hod= i have responcibiity of teachers and student")

class Fac:
  def role(self):
    print("faculty = i have to complete syllabus succussfully")

def fuct(obj):
  obj.role()
campus =[Princ(),Dean(),Hod(),Fac()]
for obj in campus:
  fuct(obj)

"""-> python did not support overloading & overriding"""

class Arithmetic:
    def add(self,a):
        print(a)
    def add(self,a,b):
        print(a+b)
    def add(self,a,b,c):
        print(a+b+c)
obj = Arithmetic()
obj.add(10)
obj.add(10,20)
obj.add(1,2,3)

class Arit:
  def add(self, a=None, b=None, c=None):
    if a!=None and b!=None:
      print(a+b)
    elif a!=None and b!=None and c!=None:
      print(a+b+c)
    else:
      print("enter atlist two arugment")
obj = Arit()
obj.add(10)
obj.add(10,20)
obj.add(1,2,3)

class Arit:
  def __init__(self):
    print("there is no argument")
  def __init__(self,a):
    print("passing one argument")
  def __init__(self,a,b):
    print("passing two argument")

  obj = Arit()
  obj = Arit(10)
  obj = Arit(2,2)

class Rbi:
  def home_loan(self):
    print("home loan = 7.5")
  def car_loan(self):
    print("car loan = 8")

class Sbi(Rbi):
  def home_loan(self):
    print("sbi provide home loan = 6.5")
    super().home_loan() #using super methot access parent class method in child class

obj = Sbi()
obj.home_loan()

#constructor overriding
class Father:
  def __init__(self):
    print("father:= i am allready at breakfast table")

class Child(Father):
  def __init__(self):
    print("child:= i will be late for breakfast")
    #super().__init__() #using super methot access parent class method in child class
obj =Child()