# -*- coding: utf-8 -*-
"""DSA DAY03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pGsYyAfApy7yIoun6_tjqFqHkp8iHt6R

dictionary
"""

mydict = {
    101:"prashant",
    102:"ashish",
    "103":"mohini",
    "104":"trivani",
    101:"ashish",
    104:"ashish",
}
print(mydict)
print()
#with the hepl of key we have to print value
#a = mydict[102]
#print(a)
print()
#mydict[102]="petar"
#print(mydict)
print()
#for x in mydict:
#  print(x)
print()
#for x in mydict.values():
 # print(x)
print()
#for x,y in mydict.items():
 # print(x,y)
print()
mydict["mobile_no"]=12345678
print(mydict)
print()

a = {(1,2):1,(2,3):2,(4,5):3}
print(a[(4,5)])

#a= {'a':1,'b':2,'c':3}
#print(a['a','b'])

arr={}
arr[1]=1
arr['1']=2
arr[1]+=1
print(arr)
sum=0
for k in arr: #k=1: k='1'
  sum+=arr[k]
print(sum)

my_dict = {}
my_dict[1] = 1
my_dict['1'] = 2
my_dict[1.0] = 4
print(my_dict)
sum =0
for k in my_dict:
  sum+=my_dict[k]
print(sum)

my_dict = {}
my_dict[(1,2,3)] = 8
my_dict[(4,2,1)] = 10
my_dict[(1,2)]=12
#print(my_dict)
sum = 0
for k in my_dict:
  sum+=my_dict[k]
print(sum)
print(my_dict)

box={}
jars={}
cretes={}
box['biscuit']=1
box['cake']=3
jars['jam']=4
cretes['box']=box
cretes['jars']=jars
#print(len(cretes[box]))

dict ={'c':97,'a':96,'b':98}
for i in sorted(dict):
  print( dict[i])

rec ={"name":"python","age":20}
r=rec.copy()
print(id(r)==id(rec))
print(id(r))
print(id(rec))

rec = {"name":"python", "age":"28", "addr":"n3","country":"usa"}
id1 = id(rec)
del rec


rec = {"name":"python", "age":"28", "addr":"n3","country":"usa"}
id2 = id(rec)
print(id1==id2)
print(id1)
print(id2)

a = {"x":20, "y":10, "z":30}
min_key = min(a, key=a.get)
print(min_key)

mydict = {
    101: "prashant",
    "professional": "developer",
    "empid": 1001
}

mydict.pop(101)
print(mydict)

for i in range(1,4):
  for j in range(1,4):

    print(i,end=" ")
  print()

n = int(input("enter the number of rows: "))
for i in range(1,n+1):
  for j in range(1,1+i):
    print(j,end=" ")
  print()

n = int(input("enter the number of rows: "))
for i in range(1,n+1):
  for j in range(1,1+i):
    print(chr(64+i),end=" ")
  print()

n = int(input("enter the number of rows: "))
for i in range(1,n+1):
  for j in range(1,n+2-i):
    print("*",end="  ")
  print()

n = int(input("enter the number of rows: "))
for i in range(1,n+1):
  for j in range(1,n+2-i):
    print(chr(64+j),end=" ")
  print()

import time
n = int(input("enter the number of rows: "))
for i in range(1,n+1):
  for j in range(1,n+2-i):
    time.sleep(1)
    print(n+1-i,end=" ")
  print()

import time
n = int(input("enter the number of rows: "))
for i in range(1,n+1):
  print(" "*(n-i),end=" ")
  for j in range(1,i+1):
    time.sleep(1)
    print("*",end=" ")
  print()

"""function in python"""

def msg():
  print("hello world!")
msg()
msg()

def arith():
  a=int(input("enter value a:"))
  b=int(input("enter value b:"))
  add=a+b
  sub=a-b
  mul=a*b
  div=a/b
  return add,sub,mul,div
#print(arith()) #calling funcion
result=arith()
print("arithmatic:",result)

"""
#how many argument we can pass in function
1. position arguments
2. keyword arguments
3. default arguments
4. variable number of arguments / variable length


"""

#positional argument
def login(username, password):
  if username==password:
    print("successfully login")
  else:
    print("invalid")
username=input("enter username:")
password=input("enter password:")
login(username, password)

#keyword argument
def login(username, password):
  if username==password:
    print("successfully login")
  else:
    print("invalid")
username=input("enter username:")
password=input("enter password:")
login(username="admin", password="admin")

#default argument
def cityName(city="goa"):
  print(city)

cityName("Delhi")
cityName("Mumbai")
cityName()

#variable number of arguments / variable length
def nameOfCitys(*city):
  print("city name:",city)

nameOfCitys("goa","nagpur","mumbai","pune")

#1. rstrip()==> to remove spaces at right hand side
#2. lstrip()==> to remove spaces at left hand side
#3. strip()==> to remove spaces both sides
pg = input("enter your programming name:")
p_name = pg.rstrip()
if p_name=='python':
  print(p_name)
elif p_name=='java':
  print(p_name)
elif p_name=='cpp':
  print(p_name)
else:
  print("wrong programming name")